alias fucking=sudo
alias bd='cd $OLDPWD'
alias ls='ls --color=auto'
alias l='ls -lh'
alias ll='l -a'
alias l.='l -d .*'
alias grep='grep --color=auto'
alias egrep='grep -E'
alias fgrep='grep -F'
alias man='LC_ALL=C LANG=C man'
alias dus='du -hsc * | sort -h'
hash colordiff 2>/dev/null && alias diff=colordiff
alias fd='find . -type d -name'
alias ff='find . -type f -name'
alias mkdir='mkdir -pv'
alias myip='curl -skL http://ipecho.net/plain; echo'
alias sha1='openssl sha1'