alias gi=git
alias gc='git commit'
alias gca='gc -a'
alias gcm='gc -m'
alias gcam='gca -m'
alias gcma='gcam'
alias gll='git log -1'
alias gllc='gll --pretty=%B'
alias gsl='git show -1'
alias gps='git push'
alias gpst='gps --tags'
alias gpl='git pull'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gs='git status'
