#!/bin/bash

args="$@"
input=$(mktemp /tmp/fzf-urxvt-input.XXXXXXXXXX) || { echo "Failed to create temp file"; exit 1; }
output=$(mktemp /tmp/fzf-urxvt-output.XXXXXXXXXX) || { echo "Failed to create temp file"; exit 1; }
while read x ; do echo "$x" >> $input ; done | cat &
urxvt -name "URxvtFZF" -e sh -c "tail -n +1 -f $input | fzf $args > $output"
cat $output
pkill -P $$
exit
