alias spacman='sudo pacman'
alias pacsyu='spacman -Syu'
alias pacs='spacman -S'
alias pacq='pacman -Q'
alias pacqe='pacman -Qe'
alias pacqm='pacman -Qm'
alias pacqem='pacman -Qem'
alias pacqs='pacman -Qs'
alias pacqi='pacman -Qi'
alias pacrns='spacman -Rns'
alias aur='PKGEXT=".pkg.tar" aurget'
alias aursyu='aur -Syu --noedit'
alias aurs='aur -S --noedit'
