alias spacman='sudo pacman'
alias pacsyu='spacman -Syu'
alias pacs='spacman -S'
alias pacq='pacman -Q'
alias pacqe='pacman -Qe'
alias pacqm='pacman -Qm'
alias pacqem='pacman -Qem'
alias pacqs='pacman -Qs'
alias pacqi='pacman -Qi'
alias pacsc='spacman -Sc'
alias pacrns='spacman -Rns'
alias pacrank='curl -s "https://www.archlinux.org/mirrorlist/?protocol=https&use_mirror_status=on" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 6 - | sudo tee /etc/pacman.d/mirrorlist'
alias aur='PKGEXT=".pkg.tar" aurget'
alias aursyu='aur -Syu --noedit'
alias aurs='aur -S --noedit'
