alias spacman='sudo pacman'
alias pacsyu='spacman -Syu'
alias pacs='spacman -S'
alias pacqe='pacman -Qe'
alias pacqm='pacman -Qm'
alias pacqs='pacman -Qs'
alias aursyu='aurget -Syu'
alias aurs='aurget -S'
