style: github
template: CHANGELOG.tpl.md
options:
  commits:
    filters:
      Type:
        - fix
        - feat
        - perf
        - refactor
        - style
        - revert
        - build
        - docs
        - ci
        - test
        - chore
  commit_groups:
    sort_by: Custom
    title_order:
      - fix
      - feat
      - perf
      - refactor
      - style
      - revert
      - build
      - docs
      - ci
      - test
      - chore
    title_maps:
      fix: Bug Fixes
      feat: Features
      perf: Performance Improvements
      refactor: Code Refactoring
      style: Styling
      revert: Reverts
      build: Build Process
      docs: Documentation
      ci: Continuous Integration
      test: Tests
      chore: Other
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?!?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
