name: Build

on:
  pull_request:
    types: ["opened", "synchronize"]
  push:
    branches:
      - main

env:
  node-version: 15.x
  ruby-version: head
  python-version: 3.x

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
      - name: Use Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Use Ruby ${{ env.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby-version }}
      - name: Install dotfiles
        run: ./script/install.sh -Bd
        env:
          DOTFILES_HOME: ${{ github.workspace }}
